nflverse/nflfastR

- DESCRIPTION
- NEWS.md
- R/helper_add_xyac.R
- R/helper_additional_functions.R
- R/helper_database_functions.R
`clean_pbp()`, `add_qb_epa()` and `add_xyac()` crashed when empty data frames were passed
This can happen if a game has finished according to the games.rds but the raw JSON isn't up on github yet
> Handle empty dfs

- DESCRIPTION
- NEWS.md
- R/helper_database_functions.R
- man/update_db.Rd
Added possibility to use other db drivers for advanced users and made some minor tweaks in `update_db()`
> More db drivers

- DESCRIPTION
- NEWS.md
- R/helper_add_ep_wp.R
Fixes for 
https://github.com/mrcaseb/fastscraper/issues/283
https://github.com/mrcaseb/fastscraper/issues/280
https://github.com/mrcaseb/nflfastR/issues/49
> more PAT fixes

- DESCRIPTION
- NEWS.md
- R/helper_add_ep_wp.R
- R/helper_database_functions.R
`update_db()` no longer falsely disconnects from external provided db connections (#102)
> Fix db drivers

- DESCRIPTION
- NEWS.md
- R/helper_database_functions.R
- R/helper_get_scheds_and_rosters.R
- man/update_db.Rd
and no longer remove complete data tables
> Add ability to update specified seasons in db

- DESCRIPTION
- R/helper_database_functions.R
- R/utils.R
> Restructure unexported helper functions

- DESCRIPTION
- NEWS.md
- R/helper_add_series_data.R
This is the first step to try to fix issues with series (#130)
> Fix series on pats

- DESCRIPTION
- NEWS.md
- R/helper_add_nflscrapr_mutations.R
- R/helper_scrape_nfl.R
> Make `penalty_fix==0` when `penalty==1` and `play_type_nfl=="PENALTY"`

- DESCRIPTION
- NEWS.md
- R/build_nflfastR_pbp.R
- R/helper_add_cp_cpoe.R
- R/helper_add_ep_wp.R
- R/helper_add_fixed_drives.R
- R/helper_add_game_data.R
- R/helper_add_nflscrapr_mutations.R
- R/helper_add_series_data.R
- R/helper_add_xpass.R
- R/helper_add_xyac.R
- R/helper_additional_functions.R
- R/helper_database_functions.R
- R/helper_decode_player_ids.R
- R/top-level_scraper.R
- R/utils.R
Added a function that is used everywhere to add the messages. With the centralized function we can easily add stuff to the messages, e.g. the current time.
While testing this I found that xpass errors if the data already includes xpass. This is fixed as well
> use own message function and fix xpass

- DESCRIPTION
- NEWS.md
- R/helper_additional_functions.R
by using possessive matches in some regular expressions
> Improve clean pbp

- CRAN-RELEASE
- DESCRIPTION
- NEWS.md
- cran-comments.md
don't merge before it is approved
> Cran 4.1.0 Release

- DESCRIPTION
- NEWS.md
- R/aggregate_game_stats.R
- R/helper_scrape_nfl.R
- man/calculate_player_stats.Rd
- vignettes/beginners_guide.Rmd
> Add `season_type` to `calculate_player_stats()` and update it in the pbp parser

- vignettes/beginners_guide.Rmd
Add some tweaks per discord discussion
> Update install and use load_pbp rather than readRDS

- DESCRIPTION
- R/load_pbp.R
- man/load_pbp.Rd
To avoid a pseudo CRAN problem
> Don't use `qs = TRUE` in `load_pbp()` example

- CRAN-RELEASE
- DESCRIPTION
- NEWS.md
- cran-comments.md
Don't merge until it's on cran
> Prepare release of v4.2.0

- NEWS.md
- R/build_nflfastR_pbp.R
- R/top-level_scraper.R
- man/build_nflfastR_pbp.Rd
- man/fast_scraper.Rd
- man/fast_scraper_roster.Rd
- man/fast_scraper_schedules.Rd
> remove deprecated `source` and `pp` arguments

- DESCRIPTION
- NEWS.md
- R/helper_scrape_gc.R
- R/helper_scrape_nfl.R
> catch "Object 'warn' not found" bug

- CRAN-RELEASE
- DESCRIPTION
- NEWS.md
- cran-comments.md
- man/nflfastR-package.Rd
- pkgdown/_pkgdown.yml
closes #291 
Don't merge until released on cran
> Release v430

- .github/workflows/pkgdown.yaml
- pkgdown/_pkgdown.yml
- vignettes/nflfastR.Rmd
I also have added a feature to preview the website for PRs. Let's see if that works with this PR
> update pkgdown yaml for new pkgdown version and BS5

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- DESCRIPTION
- NEWS.md
> nflreadr bumpver

- DESCRIPTION
- NEWS.md
- R/aggregate_game_stats.R
- man/calculate_player_stats.Rd
- man/fast_scraper_roster.Rd
> load lateral yards from nflverse releases and join player infos via `nflreadr::load_players()`

- DESCRIPTION
- NEWS.md
- R/aggregate_game_stats.R
- vignettes/beginners_guide.Rmd
- vignettes/nflfastR.Rmd
> summarise target share and air yards share correctly

- .github/workflows/pkgdown.yaml
- DESCRIPTION
- NEWS.md
- R/utils.R
- pkgdown/_pkgdown.yml
- pkgdown/extra.css
qs was listed in suggests although we didn't use it anymore. This PR removes the dep.
> Drop several dependencies

- DESCRIPTION
- NEWS.md
- R/helper_add_nflscrapr_mutations.R
- R/helper_scrape_nfl.R
> Undo manual jax fixes

- DESCRIPTION
- NEWS.md
- R/helper_add_ep_wp.R
> recognize pat preceded by timeout and penalty

- DESCRIPTION
- NEWS.md
- R/calculate_stats.R
> Fix `receiving_air_yards`

- DESCRIPTION
- NEWS.md
- R/calculate_stats.R
> Fix groups for team targets and team air yards

- DESCRIPTION
- NEWS.md
- R/calculate_stats.R
and collapses that vector to a valid search pattern string
fixes #513
> `has_id` now handles a vector of IDs to search for
