nflverse/nflfastR

DESCRIPTION, NEWS.md, R/helper_tidy_play_stats.R
Implemented new "tackle_with_assist" variables in `sum_play_stats()`.
The variables don't appear in the output as long as we don't add them to `select_variables()`
If we want them in the output we have to add them to `select_variables()` and also document them in `fast_scraper()`
=> Fix assisted tackles (#85)

DESCRIPTION, R/helper_decode_player_ids.R, man/decode_player_ids.Rd
Use purrr for small samples 
really decode all player id columns (the `tidyselect::ends_with()` part didn't work as I had it inside `tidyselect::any_of()`)
=> Optimize `decode_player_ids()`

CRAN-RELEASE, DESCRIPTION, NEWS.md, cran-comments.md
Had to resave `R/sysdata.rda` with another compression method to save filespace because the source tarball was > 5MB (causes a new CRAN NOTE). We are very close to the limit now.
=> CRAN v3.2.0

.github/workflows/R-CMD-check.yaml, .travis.yml, DESCRIPTION, NEWS.md, R/helper_add_nflscrapr_mutations.R, R/helper_scrape_cdns.R, R/helper_scrape_gc.R, R/helper_scrape_nfl.R, data-raw/wordmarks.R
This should fix the score calculation for home_team and away_team in case the posteam scores a safety
=> Offense safety fix

DESCRIPTION, R/helper_scrape_nfl.R
I didn't add this to NEWS as the normal user can't run into the corresponding bug
=> Fix safety_team for non-scoring live games

DESCRIPTION, NEWS.md, R/ep_wp_calculators.R, R/helper_add_ep_wp.R, man/calculate_expected_points.Rd, man/calculate_win_probability.Rd
This PR closes #170 
``` r
library(tidyverse)
data <- tibble::tibble(
"receive_2h_ko" = 0,
"home_team" = "SEA",
"posteam" = "SEA",
"score_differential" = 0,
"half_seconds_remaining" = 1800,
"game_seconds_remaining" = 3600,
"spread_line" = 1,
"down" = 1,
"ydstogo" = 10,
"yardline_100" = 75,
"posteam_timeouts_remaining" = 3,
"defteam_timeouts_remaining" = 3
)
nflfastR::calculate_win_probability(
data %>% mutate(vegas_wp = .9)
) %>%
pull(vegas_wp)
#> [1] 0.5147206
```
<sup>Created on 2021-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
=> Really drop existing variables in calculators

DESCRIPTION, NEWS.md, R/helper_add_xyac.R
The performance of `add_xyac()` is significantly better. Instead of using map to create the bind_col data frame we create the joined data frame now with base R functions and a left_join by index.
This is run time for the complete 2020 season
```
Unit: seconds
expr      min       lq     mean   median       uq      max neval
add_xyac 78.52598 78.52598 78.52598 78.52598 78.52598 78.52598     1
add_xyac_new 44.35558 44.35558 44.35558 44.35558 44.35558 44.35558     1
```
=> Boost xyac

DESCRIPTION, NEWS.md, R/helper_add_fixed_drives.R, R/helper_add_nflscrapr_mutations.R, R/helper_add_series_data.R
The variable `posteam` was **not** `NA` for plays with `desc %in% c("END QUARTER 2", "END QUARTER 4")`.
This broke `fixed_drive` and `fixed_drive_result`.
Since naming a `posteam` on those non-plays doesn't make sense anyway, we set it to `NA` explicitly.
=> fix posteam for end Q2 and end Q4 plays

DESCRIPTION, NEWS.md, R/aggregate_game_stats.R, man/calculate_player_stats.Rd
`calculate_player_stats` now adds dakota for players with at least 5 pass plays per game
also grouping by player_name in the final output duplicated some players with different names in the pbp (e.g. G.Minshew and G.Minshew III), instead the mode of player_name is used now
=> add dakota and fix duplicated player names

DESCRIPTION, NEWS.md, R/helper_database_functions.R
fixes #210 
if the user passes his own connection with the argument `db_connection` we should not close it after the update
There are probably users who worked around that by reconnecting to their DBs after `upodate_db()` closed the connection. 
I tested it and it's irrelevant if they try to connect to an already connected DB so we don't break any currently running scripts (I think)
=> don't disconnect custom connection

DESCRIPTION, NEWS.md, R/helper_add_nflscrapr_mutations.R
fixes #216 
here's code that scrapes total offensive yards from nfl dot com and compares it to pbp summaries with the new fix.
If the `old_new_diff == TRUE` this means, that the fix in this PR changed the output for that team. And where `diff == NA` the pbp summary and the scraped data are identical. This is TRUE for all teams so the fix works fine.
``` r
library(dplyr, warn.conflicts = FALSE)
options(dplyr.summarise.inform = FALSE)
options(tibble.print_min = 32)
options(width = 200)
passing <- rvest::read_html("https://www.nfl.com/stats/team-stats/offense/passing/2020/reg/all") %>% 
rvest::html_table() %>% 
purrr::pluck(1) %>% 
dplyr::mutate(Team = stringr::str_extract(Team, ".+(?=\\n)")) %>% 
janitor::clean_names() %>% 
dplyr::select(team:cmp, pass_yds, sck_y)
rushing <- …
```
=> Correct `yards_gained` for plays with laterals

DESCRIPTION, NEWS.md, R/aggregate_game_stats.R, man/calculate_player_stats.Rd
=> My first-ever PR: adding sack yards and total fumbles (to go with the existing fumbles lost column)

DESCRIPTION, NEWS.md, R/build_nflfastR_pbp.R, R/calculate_standings.R, R/top-level_scraper.R, R/utils.R, man/build_nflfastR_pbp.Rd, man/calculate_standings.Rd
- pbp is now returned as nflverse_data class. schedules and rosters use nflreadr anyways so this was inconsistent and we can use the class for the next point
- standings can be calculated with both pbp and schedules
=> Work with nflverse_data class

DESCRIPTION, R/helper_decode_player_ids.R
This is necessary because we may try to decode again and don't want to loose all IDs
=> decoder for 2022 ids catches multiple runs

DESCRIPTION, NEWS.md, R/aggregate_game_stats_def.R
fixes #382 
-- ensures that `fumbled_1_player_id` is always of type character,
-- allows column renaming even if data is missing by row binding a dummy tibble
=> fix def stats for missing fumble stats

DESCRIPTION, NEWS.md, R/calculate_standings.R
closes #398 
Standings calculation did not filter NA results of upcoming games. This caused the function to freeze
=> fix standings from schedules

DESCRIPTION, NEWS.md, R/helper_scrape_gc.R, R/helper_scrape_nfl.R, R/helper_tidy_play_stats.R
by looping over a list and binding it with data.table instead of dplyr.
I keep this a draft for now in case I add some more improvements
=> boost sum_play_stats 

DESCRIPTION, NEWS.md, R/aggregate_game_stats_def.R
if the pbp subset is small, there could be several columns missing which results in dplyr errors. 
This PR fixes that behavior by adding the relevant columns if they are missing
closes #410
=> `calculate_player_stats_def()` no longer errors with small subsets of pbp

DESCRIPTION, NEWS.md, R/aggregate_game_stats.R, man/calculate_player_stats.Rd
when called with argument `weekly = TRUE`
closes #397
=> `calculate_player_stats()` returns opponent team

.github/workflows/R-CMD-check.yaml, .github/workflows/pkgdown.yaml, DESCRIPTION, NEWS.md, R/helper_add_fixed_drives.R, R/report.R, README.Rmd, README.md, man/report.Rd
fixes #418 
We already incremented fixed drive on lost fumbles (with later recovery in the same play) of punts and on interceptions. 
We didn't do it for run plays nor did we for pass plays with completed passes. 
The missing run plays were the cause of #418. But there were about 20 other plays from 1999:2022 affected by not doing it on completed passes. 
I changed it to increment on punt, pass and run (for now). It fixes all relevant plays and doesn't change anything else. So this should be good to go.
=> increment fixed drive on lost fumbles with play type pass, run or punt

DESCRIPTION, NEWS.md, R/helper_additional_functions.R, R/helper_scrape_nfl.R
fixes #309 
We have this issue #309 with 2013 postseason games where the driveSequenceNumber in the plays df is NA for all plays. That prevents drive information from being joined.
In this case, we compute our own driveSequenceNumber by incrementing a counter depending on the value of driveTimeOfPossession. driveTimeOfPossession will be a constant value during a drive so this should actually be accurate
=> Fix drive sequence number

DESCRIPTION, NEWS.md, R/calculate_series_conversion_rates.R
=> Correctly aggregate conversion rates

DESCRIPTION, NEWS.md, R/aggregate_game_stats_def.R
this is part of some adjustments for #454
=> `calculate_player_stats_def` now returns `season_type` if argument `weekly` is set to `TRUE`

DESCRIPTION, NEWS.md, R/helper_decode_player_ids.R
We are going to run into the problem that some older seasons could switch player IDs if we have to reload the raw pbp data for some reason, e.g. #456. 
This messes up the current approach where we assumed that 2023+ uses Elias IDs and older seasons remain with gsis.
This PR allows nflfastR to identify the player ID as gsis or elias and decode the ID regardless of version.
=> automatically recognize ID version

DESCRIPTION, NEWS.md, R/helper_add_nflscrapr_mutations.R
There is this logic where we set kickoff_attempt to 1 mostly for plays with penalties. 
The logic uses previous play data and skips the kickoff_attempt in various situations. The logic includes that we skip a kickott_attempt if the play description of the previous play says "The game has resumed" after it has been suspended for whatever reason.
However, in 2023_13_ARI_PIT the games has been suspended twice and after the second one there ways no "The game has resumed" which made the logic set kickoff_attempt == 1 and ultimately resulted in wrong `fixed_drive` numbers (#447).
This PR explicitly avoids kickoff_attempt if the previous play description says "game has been suspended". This fixes #447 but it might fail in the future if the "The game has resumed" play is missing and the play …
=> no kick off if previous play is weather delay

DESCRIPTION, NEWS.md, R/helper_tidy_play_stats.R
=> Fill punter info on blocked punts

DESCRIPTION, NEWS.md, R/helper_add_nflscrapr_mutations.R
Here is an example of plays where nflfastR didn't parse the penalty type
=> Add new penalty type from dynamic kickoff rules

DESCRIPTION, NEWS.md, R/helper_add_ep_wp.R, nflfastR.Rproj
Fixes #502 
vegas_wp variables were completely broken when spread_line data is NA. 
The result is a bouncing win probability that doesn't make any sense. 
We decided to avoid this extreme result by setting `NA` spread lines to 1.5 (~ home field advantage). However, since that is not the actual line, we warn the user and ask them to create an issue. 
```
✖ The following game is missing valid spread lines: "2024_17_ARI_LA".
✖ nflfastR will manually set the spread for the home team to "1.5" points!
! If you see this, please reach out to the package maintainers <https://github.com/nflverse/nflfastR/issues>
```
The result of the manual overwrite looks far better, tho it is still wrong
=> Catch missing `spread_line` data

DESCRIPTION, NEWS.md, R/calculate_standings.R, man/calculate_standings.Rd
closes #491 
This PR deprecates `calculate_standings()`. The deprecation message will tell the user to use `nflseedR::nfl_standings()` instead.
I decided against re-exporting `nfl_standings`. User should just go the nflseedR way.
=> deprecate standings
